### ISSUE TITLE
Make Selection feature more intuitive

### ISSUE THREAD

**Issue by tmonsereenusorn** [tmonsereenusorn/moosh#6]
Per presentation feedback, we should make the select/deselect function more intuitive. This can include:

1. Add a button for selecting and deselecting all songs (if all songs are selected, pressing the button will deselect all songs. Otherwise, pressing the button will reselect all songs).
2. When a song is deselected, dim the track card to indicate that the song is to be removed/regenerated
3. Add a tooltip when hovering over the regenerate button saying:
- If all songs are selected/deselected: "Click to generate a new playlist on the same prompt."
- Else: "Click to replace unselected songs with new ones."
4. Add a tooltip when hovering over the export button saying "Export all selected songs to a Spotify playlist"

**Comment by tmonsereenusorn** [comment]
Potential alternative implementation to tooltip:
- Dim regenerate button when all songs are selected
- Say "Regenerate {x} songs" as x songs are deselected

**Comment by gcockroft** [comment]
Design for selection box.
<img width="802" alt="Screenshot 2024-04-05 at 12 19 54 AM" src="https://github.com/tmonsereenusorn/moosh/assets/77020027/f260cdd5-df6b-4b77-ace4-1d694759cd0e">

1. Single “indeterminate checkbox” at the top renders when 0 < x < n songs are selected. When 0 selected, empty checkbox. When n selected, filled checkbox. I took this design from Notion and saw it when i google around a bit. When ind. checkbox is clicked, all songs become selected, and ind. checkbox become regular filled checkbox. Modeled off Notion select all behavior.
2. Count of number of songs currently selected. Changes as songs are selected / deselected
3. Moved prompt up so it's on a separate line than the selection.


This fixes the accessibility with minimal code a pretty good job of fixing accessibility as the “x songs selected” next to the checkbox makes it evident you can select, and the UI is minimal.
